---
title: ''
output: pdf_document
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(echo = FALSE)
```

```{r}
noneCore <- read.csv('sev048_phenology_20130412.txt', as.is = TRUE)
core <- read.csv('sev137_phenologycore_20170203.csv', as.is = TRUE)
sppCodes <- read.csv('sev_plant_list.csv', as.is = TRUE)

dwJuly <- unique(noneCore$species_code[noneCore$site == 'dw' & 
                                           substring(noneCore$date, 5, 6) == '07' &
                                           !(noneCore$dormant == 'y' | 
                                                 noneCore$dead == 'y' |
                                                 noneCore$not.present == 'y')])

blueJuly <- unique(core$SPECIES[core$SITE == 'B' & 
                                    gsub('/.*', '', core$DATE) == '7' &
                                    !(core$FOLIAGE != 'Z' | core$FF != 'Z')])

blackJuly <- unique(core$SPECIES[core$SITE == 'G' & 
                                     gsub('/.*', '', core$DATE) == '7' &
                                     !(core$FOLIAGE != 'Z' | core$FF != 'Z')])
```


## Deep Well July

```{r}
kable(sppCodes[sort(na.omit(match(dwJuly, sppCodes$Code))), c(1, 3, 4, 2)], 
      row.names = FALSE)
```

\pagebreak

## Black Grama Core Site July

```{r}
kable(sppCodes[sort(na.omit(match(blueJuly, sppCodes$Code))), c(1, 3, 4, 2)], 
      row.names = FALSE)
```

\pagebreak

## Blue Grama Core Site July

```{r}
kable(sppCodes[sort(na.omit(match(blueJuly, sppCodes$Code))), c(1, 3, 4, 2)], 
      row.names = FALSE)
```
